### ISSUE TITLE
爆弾

### ISSUE THREAD

**Issue by c0a21160** [kouki0412/ProjExD#11]
https://github.com/kouki0412/ProjExD/blob/c722dc3ec4a3602e329a3148f500c49d10ccec2b/ex04/dodge_bomb.py#L9
初めは爆弾の増やせる数を10個にしていたが、判定が重なってしまうせいで増えすぎてしまうとお聞きしたので、クールタイムなどを設けると上手く増やすことが出来ると思います。

**Comment by kouki0412** [comment]
ありがとうございます。その通りなのですが、時間がないので後ほど修正させていただきます
