### ISSUE TITLE
爆弾が増えない

### ISSUE THREAD

**Issue by C0A21007** [kouki0412/ProjExD#12]
https://github.com/kouki0412/ProjExD/blob/c722dc3ec4a3602e329a3148f500c49d10ccec2b/ex04/dodge_bomb.py#L113
爆弾の数が２個以上に増えないのですが、仕様でしょうか。仕様でしたらすみません。

**Comment by kouki0412** [comment]
爆弾が一気に増えすぎてしまうのをいったん防ぐための応急処置です。
そのため、一応仕様ですが、後ほど修正させていただきます。
