### ISSUE TITLE
謎のコメントアウト

### ISSUE THREAD

**Issue by c0a2104709** [kouki0412/ProjExD#13]
https://github.com/kouki0412/ProjExD/blob/c722dc3ec4a3602e329a3148f500c49d10ccec2b/ex04/dodge_bomb.py#L99
99行目のコメントアウトされてある文は何かのメモですか

**Comment by kouki0412** [comment]
これは、最初にデバックするときにコメントアウトしたのをそのままにしていました。
他のデバック用出力も削除しました。ありがとうございます。
