### ISSUE TITLE
爆弾を増やせる数

### ISSUE THREAD

**Issue by C0A21071** [kouki0412/ProjExD#14]
https://github.com/kouki0412/ProjExD/blob/edf2b5975429798ca9326897ae2b67bc6510ced1/ex04/dodge_bomb.py#L10

READMEなどに、爆弾を増やせる上限個数を書かないと、バグで増やせないのか勘違いしてしまうかもしれません。

**Comment by kouki0412** [comment]
ありがとうございます。READMEに追加させていただきました。
