### ISSUE TITLE
読み方

### ISSUE THREAD

**Issue by c0a21160** [kouki0412/ProjExD#2]
https://github.com/kouki0412/ProjExD/blob/d10823a79d3422d61615d8f74e50ba98e611c312/ex01/quiz.py#L25
回答欄にワカメとマスオを漢字表記で書いてもよいと思った

**Comment by kouki0412** [comment]
quiz.pyのissueでもいいんでしたっけ...。怪しいのでコードの変更は行わないでおきます。
コメントありがとうございます。
