### ISSUE TITLE
def

### ISSUE THREAD

**Issue by c0a21160** [kouki0412/ProjExD#8]
https://github.com/kouki0412/ProjExD/blob/945bc6edfede3545c0dc8252c408e24f772f0948/ex03/maze.py#L82
READMEの表記がばぐっていた
とても複雑な機能を作成できていた。ここから定義されていた内容が同じような繰り返しなのでまとめられたら更によいと思った。

**Comment by kouki0412** [comment]
READMEの表記バグの報告ありがとうございます。(issueを見る前に直していました)
また、指摘していただいた場所に関してはそもそも実装が難しい上、dict型で無理やり実装した場合分かりにくくなってしまうので今回は修正しないことにします。ありがとうございます。
